// Final analysis report display

export default function ReportView({ report, jobId }) {
  if (!report) return null

  const s = report.summary || {}
  const results = report.test_results || []

  const handleDownload = () => {
    window.open(`/report/${jobId}/pdf`, '_blank')
  }

  return (
    <div className="card">
      <p className="card-title">Final Report — {report.repo || 'unknown'}</p>

      <div className="report-summary-grid">
        <div className="stat-box">
          <div className="stat-val">{s.files_analyzed ?? 0}</div>
          <div className="stat-label">Files</div>
        </div>
        
        <div className="stat-box">
          <div className="stat-val">{s.tests_generated ?? 0}</div>
          <div className="stat-label">Tests</div>
        </div>
        
        {/* 
          Passed tests box with green styling
          Shows number of tests that passed
        */}
        <div className="stat-box green">
          <div className="stat-val">{s.passed ?? 0}</div>
          <div className="stat-label">Passed</div>
        </div>
        
        {/* 
          Failed tests box with red styling
          Shows number of tests that failed
        */}
        <div className="stat-box red">
          <div className="stat-val">{s.failed ?? 0}</div>
          <div className="stat-label">Failed</div>
        </div>
        
        {/* 
          Errors box with yellow/warning styling
          Shows number of test execution errors
        */}
        <div className="stat-box yellow">
          <div className="stat-val">{s.errors ?? 0}</div>
          <div className="stat-label">Errors</div>
        </div>
      </div>

      {/* 
        Detailed test results table
        Only show if there are test results to display
      */}
      {results.length > 0 && (
        <div style={{ overflowX: 'auto' }}>
          <table className="result-table">
            <thead>
              <tr>
                <th>Function</th>
                <th>File</th>
                <th>Status</th>
                <th>Notes</th>
              </tr>
            </thead>
            <tbody>
              {results.map((r, i) => {
                // Determine if test passed or failed
                const passed = r.passed && !r.failed
                
                return (
                  <tr key={i}>
                    {/* Function name being tested */}
                    <td>{r.function || '—'}</td>
                    
                    {/* Source file path (dimmed) */}
                    <td style={{ color: 'var(--text-muted)' }}>
                      {r.target_file || '—'}
                    </td>
                    
                    {/* 
                      Status badge
                      Color-coded: green for PASS, red for FAIL
                    */}
                    <td>
                      <span className={`badge ${passed ? 'pass' : 'fail'}`}>
                        {passed ? 'PASS' : 'FAIL'}
                      </span>
                    </td>
                    
                    {/* 
                      Triage notes
                      Human-readable explanation of test outcome
                      Generated by Triage agent (e.g., "Assertion failed...")
                    */}
                    <td className="triage-note">{r.triage || ''}</td>
                  </tr>
                )
              })}
            </tbody>
          </table>
        </div>
      )}

      {/* 
        Download PDF button
        Triggers download of the full PDF report
      */}
      <button
        id="download-report-btn"
        className="btn dl-btn"
        onClick={handleDownload}
        title="Download PDF report"
      >
        ↓ Download PDF Report
      </button>

      {/* 
        Generation timestamp
        Shows when the report was created (in local time)
      */}
      <p style={{ fontSize: '0.7rem', color: 'var(--text-muted)', marginTop: '0.5rem' }}>
        Generated at {report.generated_at ? new Date(report.generated_at).toLocaleString() : '—'}
      </p>
    </div>
  )
}
