# Test Writer Agent: Generate pytest test stubs and enhance with Gemini 1.5 Flash

import textwrap
import sys

from utils.config import get_gemini_api_key
from utils.gemini_client import gemini_chat


def run_test_writer(state: dict) -> dict:
    """Generate test stubs from analysis results and optionally enhance with Gemini."""
    analysis = state.get("analysis", {})
    if not isinstance(analysis, dict):
        analysis = {}

    modules = analysis.get("modules", []) or []
    tests = []

    for mod in modules:
        if not isinstance(mod, dict):
            continue
        for func in mod.get("functions", []):
            if not isinstance(func, dict):
                continue
            # Skip private/dunder helpers — they're rarely testable standalone
            fname = func.get("name", "")
            if fname.startswith("__") and fname.endswith("__"):
                continue
            test_code = _generate_stub(mod.get("path", "unknown.py"), func)
            tests.append({
                "target_file": mod.get("path", "unknown.py"),
                "function": fname,
                "test_code": test_code,
            })

    gemini_enabled = bool(get_gemini_api_key())
    print(f"[TEST_WRITER] Gemini API available: {gemini_enabled}", file=sys.stderr)
    print(f"[TEST_WRITER] Total stubs generated: {len(tests)}", file=sys.stderr)

    if gemini_enabled and tests:
        print(f"[TEST_WRITER] Enhancing up to 30 tests with Gemini 1.5 Flash...", file=sys.stderr)
        tests = _llm_enhance(tests, analysis)
    else:
        print("[TEST_WRITER] Skipping LLM enhancement (no key or no tests)", file=sys.stderr)

    return {**state, "tests": tests}


def _generate_stub(filepath: str, func_info: dict) -> str:
    """Create a basic pytest stub for a function."""
    func_name = func_info.get("name", "unknown_function")
    args = func_info.get("args", []) or []
    docstring = func_info.get("docstring", "")
    lineno = func_info.get("lineno", "?")

    module_path = filepath.replace("/", ".").replace("\\", ".")
    if module_path.endswith(".py"):
        module_path = module_path[:-3]

    # Build placeholder argument values
    arg_vals = []
    for arg in args:
        if arg in ("self", "cls"):
            continue
        arg_vals.append("None")

    call_str = f"{func_name}({', '.join(arg_vals)})"

    docstring_comment = f"    # Function docstring: {docstring[:100]}" if docstring else ""

    return textwrap.dedent(f"""\
        # Auto-generated by AgentQA Test Writer Agent
        # Target: {func_name} (line {lineno}) in {filepath}
        import pytest
        {docstring_comment}
        # TODO: adjust import path — e.g.: from {module_path} import {func_name}

        def test_{func_name}_normal():
            # Normal input — happy path
            assert True  # replace with: result = {call_str}; assert result ...

        def test_{func_name}_boundary():
            # Boundary values (zero, max, min, edge lengths)
            assert True

        def test_{func_name}_null_empty():
            # Null / empty inputs
            assert True

        def test_{func_name}_type_mismatch():
            # Type mismatch — wrong argument types
            assert True

        def test_{func_name}_logic_edge():
            # Logic-specific edge case
            assert True
    """)


# ──────────────────────────────────────────────
# LLM Enhancement using Gemini 1.5 Flash
# ──────────────────────────────────────────────

SYSTEM_PROMPT = (
    "You are an expert Python QA engineer writing pytest test suites. "
    "Given a function stub, rewrite it with realistic, specific pytest assertions. "
    "You MUST cover ALL FIVE of these test branches:\n"
    "1. Normal input — a typical valid call that should succeed\n"
    "2. Boundary values — zero, empty string, max/min numeric limits, single-element lists\n"
    "3. Null/empty inputs — None, '', [], {}, 0\n"
    "4. Type mismatch — passing wrong types (e.g., str where int expected) and asserting TypeError or similar\n"
    "5. Logic-specific edge cases — inverting conditions, negative numbers, very large values\n\n"
    "Rules:\n"
    "- Return ONLY valid Python code — no explanations, no markdown fences.\n"
    "- Each test function must have at least one non-trivial assert statement.\n"
    "- If the function cannot be imported without the actual module, mock it with unittest.mock.\n"
    "- Keep each test function focused on exactly one branch.\n"
    "- Use descriptive assert messages: assert result == expected, f'got {result}'\n"
)


def _llm_enhance(tests: list[dict], analysis: dict) -> list[dict]:
    """Enhance test stubs with Gemini 1.5 Flash — up to 30 tests."""
    gemini_key = get_gemini_api_key()
    if not gemini_key:
        return tests

    repo_name = analysis.get("repo", "unknown")
    limit = min(len(tests), 30)

    print(f"[TEST_WRITER] Enhancing {limit} tests for repo={repo_name}", file=sys.stderr)

    for i in range(limit):
        test = tests[i]
        func_name = test.get("function", "unknown")
        target_file = test.get("target_file", "unknown.py")

        print(f"[TEST_WRITER] Enhancing {i+1}/{limit}: {func_name} in {target_file}", file=sys.stderr)

        user_message = (
            f"Repository: {repo_name}\n"
            f"Source file: {target_file}\n"
            f"Function under test: {func_name}\n\n"
            f"Existing stub to rewrite:\n```python\n{test['test_code']}\n```\n\n"
            "Rewrite the stub with all 5 test branches as instructed. "
            "Return only valid Python code."
        )

        messages = [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_message},
        ]

        try:
            enhanced = gemini_chat(messages, temperature=0.25, max_tokens=600)
            # Strip markdown code fences if model wraps the output
            enhanced = _strip_code_fences(enhanced)
            if enhanced and len(enhanced) > 50:
                tests[i]["test_code"] = enhanced
                tests[i]["llm_enhanced"] = True
                print(f"[TEST_WRITER] ✓ Test {i+1} enhanced ({len(enhanced)} chars)", file=sys.stderr)
            else:
                print(f"[TEST_WRITER] ✗ Test {i+1} response too short, keeping stub", file=sys.stderr)
        except Exception as e:
            print(f"[TEST_WRITER] ✗ Test {i+1} enhancement failed: {type(e).__name__}: {e}", file=sys.stderr)
            tests[i]["llm_error"] = str(e)

    return tests


def _strip_code_fences(code: str) -> str:
    """Remove ```python ... ``` or ``` ... ``` wrappers from LLM output."""
    lines = code.strip().splitlines()
    if lines and lines[0].startswith("```"):
        lines = lines[1:]
    if lines and lines[-1].strip() == "```":
        lines = lines[:-1]
    return "\n".join(lines).strip()
